export default {
  landscape: {
    1: {
      1: ["top", "bottom", "left", "right"],
    },
    2: {
      1: ["top", "bottom", "left"],
      2: ["top", "bottom", "right"],
    },
    3: {
      1: ["top", "bottom", "left"],
      2: ["top", "bottom"],
      3: ["top", "bottom", "right"],
    },
    4: {
      1: ["top", "bottom", "left"],
      2: ["top", "bottom"],
      3: ["top", "bottom"],
      4: ["top", "bottom", "right"],
    },
    5: {
      1: ["top", "left"],
      2: ["top"],
      3: ["top", "right"],
      4: ["bottom"],
      5: ["bottom", "left"],
    },
    6: {
      1: ["top", "left"],
      2: ["top"],
      3: ["top", "right"],
      4: ["bottom", "right"],
      5: ["bottom"],
      6: ["bottom", "left"],
    },
    7: {
      1: ["top", "left"],
      2: ["top"],
      3: ["top"],
      4: ["top", "right"],
      5: ["bottom"],
      6: ["bottom"],
      7: ["bottom", "left"],
    },
    8: {
      1: ["top", "left"],
      2: ["top"],
      3: ["top"],
      4: ["top", "right"],
      5: ["bottom", "right"],
      6: ["bottom"],
      7: ["bottom"],
      8: ["bottom", "left"],
    },
  },
  portrait: {
    1: {
      1: ["top", "bottom", "left", "right"],
    },
    2: {
      1: ["top", "left", "right"],
      2: ["bottom", "left", "right"],
    },
    3: {
      1: ["top", "left"],
      2: ["top", "right"],
      3: ["bottom", "left"],
    },
    4: {
      1: ["top", "left"],
      2: ["top", "right"],
      3: ["bottom", "right"],
      4: ["bottom", "left"],
    },
    5: {
      1: ["top", "left"],
      2: ["top", "right"],
      3: ["right"],
      4: ["bottom", "left"],
      5: ["left"],
    },
    6: {
      1: ["top", "left"],
      2: ["top", "right"],
      3: ["right"],
      4: ["bottom", "right"],
      5: ["bottom", "left"],
      6: ["left"],
    },
    7: {
      1: ["top", "left"],
      2: ["top", "right"],
      3: ["right"],
      4: ["right"],
      5: ["bottom", "left"],
      6: ["left"],
      7: ["left"],
    },
    8: {
      1: ["top", "left"],
      2: ["top", "right"],
      3: ["right"],
      4: ["right"],
      5: ["bottom", "right"],
      6: ["bottom", "left"],
      7: ["left"],
      8: ["left"],
    },
  },
};
